### ISSUE TITLE
make error with gvcftools-0.16.1

### ISSUE THREAD

**Issue by yingchen69** [sequencing/gvcftools#5]
Hi,

I got some error message when I tried to install gvcftools-0.16.1 although all commands seemed to be in place.

    test/parse_util_test.cpp:22: error: 'illumina' has not been declared
    test/parse_util_test.cpp:22: error: 'blt_util' is not a namespace-name
    test/parse_util_test.cpp:22: error: expected namespace-name before ';' token
    test/parse_util_test.cpp: In member function 'void parse_util::test_parse_double_inf::test_method()':
    test/parse_util_test.cpp:184: error: 'isinf' is not a member of 'std'
    make[2]: *** [test/parse_util_test.o] Error 1
    make[2]: Leaving directory `/home/yc790/apps/gvcftools-0.16.1/src/libutil'
    make[1]: *** [test] Error 2
    make[1]: Leaving directory `/home/yc790/apps/gvcftools-0.16.1/src'
    make: *** [test] Error 2

I did not have such errors when I installed gvcftools-0.16.

Any suggestion?

Thanks a lot,

Ying

**Comment by ctsa** [comment]
Looks like our auto-testing was skipping the unit tests. Fixed in version bump (v0.16.2). Closed at 6d6e12bf3ba5efc43500c9155e4aa41e361347a3
