### ISSUE TITLE
Small and Capital characters in Output vcf from gvcf (by using the break_block)

### ISSUE THREAD

**Issue by amitgsir** [sequencing/gvcftools#6]
Hi,

I am using break_block to receive the genomic entry in for each position in a bed file.

It is giving the output correctly, just one question.

For most of the genomic positions, it gives Ref/Alt in capital characters while for some entries in the small characters. Do you know why??

E.g. vcf file after break_block:

chrM    2456    .   G   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1997:0:1955:0,0,0
chrM    2464    .   A   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1997:0:1955:0,0,0
chrM    2470    .   A   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1997:0:1955:0,0,0
chrM    2477    .   T   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1997:0:1955:0,0,0
chrM    2483    .   A   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1997:0:1955:0,0,0
chrM    2516    .   C   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2572    .   C   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2581    .   C   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2582    .   T   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2595    .   **g**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2596    .   **t**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2612    .   **t**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2623    .   **g**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2626    .   **c**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2630    .   **t**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2639    .   **c**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2680    .   **a**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2690    .   **c**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2702    .   **g**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2706    .   **a**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2707    .   **t**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2746    .   **t**   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2753    .   G   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2755    .   A   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2758    .   C   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2766    .   A   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2768    .   C   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2772    .   C   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2789    .   A   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0
chrM    2800    .   A   <NON_REF>   .   .   .   GT:DP:GQ:MIN_DP:PL  0/0:1998:0:1863:0,0,0

while the gvcf file for this region is:

chrM    527     .       C       <NON_REF>       .       .       END=527 GT:DP:GQ:MIN_DP:PL      0/0:101:0:101:0,0,0
chrM    528     .       G       <NON_REF>       .       .       END=535 GT:DP:GQ:MIN_DP:PL      0/0:0:99:0:0,292,0
chrM    536     .       C       <NON_REF>       .       .       END=537 GT:DP:GQ:MIN_DP:PL      0/0:105:0:105:0,0,0
chrM    538     .       C       <NON_REF>       .       .       END=539 GT:DP:GQ:MIN_DP:PL      0/0:0:99:0:0,295,0
chrM    540     .       A       <NON_REF>       .       .       END=540 GT:DP:GQ:MIN_DP:PL      0/0:95:0:95:0,0,0
chrM    541     .       T       <NON_REF>       .       .       END=542 GT:DP:GQ:MIN_DP:PL      0/0:0:99:0:0,316,0
chrM    543     .       C       <NON_REF>       .       .       END=544 GT:DP:GQ:MIN_DP:PL      0/0:108:0:108:0,0,0
chrM    545     .       C       <NON_REF>       .       .       END=555 GT:DP:GQ:MIN_DP:PL      0/0:0:99:0:0,283,0
chrM    556     .       A       C,<NON_REF>     -nan    PASS    DP=2104;MQ=60.00;MQRankSum=0.000;ReadPosRankSum=0.000   GT:AD:DP:GQ:PL:SB       0/0:1946,40,0:1986:99:0,343,4493,350,4496,4503:0,0,0,0
chrM    557     .       A       <NON_REF>       .       .       END=2353        GT:DP:GQ:MIN_DP:PL      0/0:1998:0:1680:0,0,0
chrM    2354    .       C       T,<NON_REF>     5510.13 PASS    DP=1993;MQ=60.00        GT:AD:DP:GQ:PL:SB       1/1:0,1992,0:1992:99:5966,426,0,5966,426,5966:0,0,0,0
chrM    2355    .       A       <NON_REF>       .       .       END=2484        GT:DP:GQ:MIN_DP:PL      0/0:1997:0:1955:0,0,0
chrM    2485    .       C       T,<NON_REF>     5404.17 PASS    DP=1993;MQ=60.00        GT:AD:DP:GQ:PL:SB       1/1:0,1991,0:1991:99:5846,413,0,5849,420,5856:0,0,0,0
**chrM    2486    .       C       <NON_REF>       .       .       END=3008        GT:DP:GQ:MIN_DP:PL      0/0:1998:0:1863:0,0,0**
chrM    3009    .       C       A,<NON_REF>     -nan    PASS    DP=2147;MQ=59.81;MQRankSum=0.000;ReadPosRankSum=0.000   GT:AD:DP:GQ:PL:SB       0/0:1992,7,0:1999:99:0,425,6536,439,6541,6555:0,0,0,0
chrM    3010    .       C       <NON_REF>       .       .       END=3011        GT:DP:GQ:MIN_DP:PL      0/0:143:99:143:0,120,1800
chrM    3012    .       G       A,<NON_REF>     5765.14 PASS    DP=1993;MQ=59.80        GT:AD:DP:GQ:PL:SB       1/1:0,1991,0:1991:99:6192,397,0,6195,441,6239:0,0,0,0
chrM    3013    .       A       <NON_REF>       .       .       END=4883        GT:DP:GQ:MIN_DP:PL      0/0:1998:0:1584:0,0,0
chrM    4884    .       C       T,<NON_REF>     5273.34 PASS    DP=1981;MQ=56.51        GT:AD:DP:GQ:PL:SB       1/1:0,1978,0:1978:99:5684,380,0,5687,419,5725:0,0,0,0

**Comment by ctsa** [comment]
Hi Amit,

This should probably be reflecting a case difference from the reference. Regardkess, this is an issue that should be fixed. Could you check your reference and confirm whether it switches to lower case at the point where break_blocks changes to lower case in your example? If so, I can look into a quick patch.

-Chris

**Comment by shankarajays** [comment]
Very likely that the lowercase reference bases indicate repeat-masked
sequence.

Shankar

**Comment by amitgsir** [comment]
Hi Chris and Shankar,

I checked the reference genome hg19 for the positions with lower case.

After initial check, it looks like the "Repeating elements by repeatmasker" in the hg19 are the bases in the lower case.

Amit
